### ISSUE TITLE
How to generate report with all data from sonarqube scan

### ISSUE THREAD

**Issue by sgcsekar1** [soprasteria/sonar-report#194]
Hello, I tried to generate the report (from self hosted sonarqube server )with below parameters. But this produced an empty report. Please suggest me missing parameters to generate report with all data from sonarqube

sonar-report --sonarurl="https://sonarqube_self_host_server.com"  --sonarusername="username" --sonarpassword="password" --sonarcomponent="key-componentname"  --project="project-name"  --   --branch="feature/br_name"   --output="c:\temp\sonar-report_sonar-report.html

**Comment by ptrovatelli** [comment]
is the report completely empty (file of size 0) or is it correctly formatted but with no issue inside? 

do you have vulnerabilities or only bugs? try the `--allbugs` flag to include all bugs, not only vulnerabilities

try to remove all filters like the one on the branch name to see if the problem comes from that

I noticed an problem in your command, maybe bad copy paste? ` -- --branch="feature/br_name"` . There shouldn't be this `--` before `--branch`

**Comment by sgcsekar1** [comment]
I am able to generate the report using --allbugs flag. Thank you.
Are there any option to include code coverage details?
